'use strict';
const $=id=>document.getElementById(id),uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
let state={nodes:[{id:uid(),x:100,y:100,title:'Projet principal',body:'Vision :\n\nHypothèses :\n\nFormules / valeurs :\n\nDécisions :'}],links:[],messages:[]};
function valid(s){return s&&Array.isArray(s.nodes)&&s.nodes.length<=1000&&s.nodes.every(n=>typeof n.id==='string'&&Number.isFinite(n.x)&&Number.isFinite(n.y)&&typeof n.title==='string'&&typeof n.body==='string')&&new Set(s.nodes.map(n=>n.id)).size===s.nodes.length&&Array.isArray(s.links)&&s.links.every(l=>Array.isArray(l)&&l.length===2&&l.every(id=>s.nodes.some(n=>n.id===id)))&&Array.isArray(s.messages)&&s.messages.every(m=>typeof m==='string')}
try{const s=JSON.parse(localStorage.getItem('workshop-v1'));if(valid(s))state=s}catch{}
function status(t){$('status').textContent=t}function save(){try{localStorage.setItem('workshop-v1',JSON.stringify(state));status('Tableau et messages sauvegardés sur cet appareil.')}catch{status('Sauvegarde impossible : exportez votre tableau.')}}
let scale=1,px=0,py=0,source=null;
function transform(){$('world').style.transform='translate('+px+'px,'+py+'px) scale('+scale+')'}
function draw(){$('lines').replaceChildren();state.links.forEach((l,i)=>{const a=state.nodes.find(n=>n.id===l[0]),b=state.nodes.find(n=>n.id===l[1]);if(!a||!b)return;const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d','M '+(a.x+150)+' '+(a.y+110)+' L '+(b.x+150)+' '+(b.y+110));p.setAttribute('stroke','#82cbb9');p.setAttribute('stroke-width','10');p.setAttribute('fill','none');p.style.cursor='pointer';p.style.pointerEvents='stroke';p.onpointerdown=e=>e.stopPropagation();p.onclick=()=>{state.links.splice(i,1);draw();save()};$('lines').append(p)})}
function render(){$('nodes').replaceChildren();for(const n of state.nodes){const el=document.createElement('article');el.className='node';el.style.left=n.x+'px';el.style.top=n.y+'px';el.innerHTML='<div class="row"><button class="handle" aria-label="Déplacer">☰</button><input aria-label="Titre"><button class="del" aria-label="Supprimer">×</button></div><textarea aria-label="Contenu"></textarea><button class="link">Relier cette case</button>';el.querySelector('input').value=n.title;el.querySelector('textarea').value=n.body;el.querySelector('input').oninput=e=>{n.title=e.target.value;save()};el.querySelector('textarea').oninput=e=>{n.body=e.target.value;save()};el.querySelector('.del').onclick=()=>{state.nodes=state.nodes.filter(v=>v.id!==n.id);state.links=state.links.filter(l=>!l.includes(n.id));if(source===n.id)source=null;render();save()};if(source===n.id)el.classList.add('selected');el.querySelector('.link').onclick=()=>{if(!source){source=n.id;el.classList.add('selected');status('Cliquez sur Relier dans la case de destination, ou à nouveau ici pour annuler.')}else{if(source!==n.id&&!state.links.some(l=>l.includes(source)&&l.includes(n.id)))state.links.push([source,n.id]);source=null;render();save()}};const h=el.querySelector('.handle');let drag=null;h.onpointerdown=e=>{e.preventDefault();e.stopPropagation();h.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,y:e.clientY}};h.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;n.x+=(e.clientX-drag.x)/scale;n.y+=(e.clientY-drag.y)/scale;drag.x=e.clientX;drag.y=e.clientY;el.style.left=n.x+'px';el.style.top=n.y+'px';draw()};h.onpointerup=h.onpointercancel=()=>{drag=null;save()};$('nodes').append(el)}draw();renderMessages()}
function renderMessages(){$('messages').replaceChildren();for(const m of state.messages){const p=document.createElement('p');p.textContent=m;$('messages').append(p)}}
const pointers=new Map();let prev=null;
function gesture(){const p=[...pointers.values()];return p.length===1?{x:p[0].x,y:p[0].y,d:0}:{x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2,d:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}}
$('view').onpointerdown=e=>{if(e.target.closest('.node'))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});$('view').setPointerCapture(e.pointerId);prev=gesture()};
$('view').onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const g=gesture();if(prev){px+=g.x-prev.x;py+=g.y-prev.y;if(g.d&&prev.d)zoom(scale*g.d/prev.d,g.x,g.y);transform()}prev=g};
function end(e){pointers.delete(e.pointerId);prev=pointers.size?gesture():null}$('view').onpointerup=end;$('view').onpointercancel=end;
function zoom(s,x,y){s=Math.max(.15,Math.min(3,s));const r=$('view').getBoundingClientRect(),a=x-r.left,b=y-r.top;px=a-(a-px)*s/scale;py=b-(b-py)*s/scale;scale=s;transform()}
$('view').addEventListener('wheel',e=>{if(e.target.closest('textarea'))return;e.preventDefault();zoom(scale*Math.exp(-e.deltaY*.0015),e.clientX,e.clientY)},{passive:false});
function step(f){const r=$('view').getBoundingClientRect();zoom(scale*f,r.left+r.width/2,r.top+r.height/2)}$('plus').onclick=()=>step(1.2);$('minus').onclick=()=>step(1/1.2);
$('fit').onclick=()=>{if(!state.nodes.length)return;const x=Math.min(...state.nodes.map(n=>n.x)),y=Math.min(...state.nodes.map(n=>n.y)),w=Math.max(...state.nodes.map(n=>n.x+300))-x,h=Math.max(...state.nodes.map(n=>n.y+320))-y;scale=Math.max(.15,Math.min(1,($('view').clientWidth-40)/w,($('view').clientHeight-40)/h));px=($('view').clientWidth-w*scale)/2-x*scale;py=($('view').clientHeight-h*scale)/2-y*scale;transform()};
$('add').onclick=()=>{state.nodes.push({id:uid(),x:($('view').clientWidth/2-px)/scale-150,y:($('view').clientHeight/2-py)/scale-100,title:'Nouvelle case',body:'Notes :\n\nFormules / valeurs :\n\nDécisions :'});render();save()};
$('chat').onsubmit=e=>{e.preventDefault();const t=$('message').value.trim();if(!t)return;state.messages.push(t);$('message').value='';renderMessages();save()};
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000)}
$('export').onclick=()=>download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'workshop.json');
$('importButton').onclick=()=>$('import').click();$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const s=JSON.parse(await f.text());if(!valid(s))throw Error();if(!confirm('Remplacer le tableau et les messages actuels ?'))return;state=s;source=null;render();save();$('fit').click()}catch{status('Fichier de tableau invalide.')}finally{e.target.value=''}};
let db;
try{const req=indexedDB.open('workshop-documents',1);req.onupgradeneeded=()=>req.result.createObjectStore('files',{keyPath:'id'});req.onsuccess=()=>{db=req.result;listFiles()};req.onerror=()=>status('Stockage des documents indisponible.')}catch{status('Stockage des documents indisponible dans ce navigateur.')}
function listFiles(){const r=db.transaction('files').objectStore('files').getAll();r.onsuccess=()=>{$('files').replaceChildren();for(const item of r.result){const p=document.createElement('p'),b=document.createElement('button'),d=document.createElement('button');b.textContent=item.file.name;b.onclick=()=>download(item.file,item.file.name);d.textContent='×';d.setAttribute('aria-label','Supprimer '+item.file.name);d.onclick=()=>{const t=db.transaction('files','readwrite');t.objectStore('files').delete(item.id);t.oncomplete=listFiles};p.append(b,d);$('files').append(p)}}}
function addFiles(files){if(!db){status('Stockage des fichiers indisponible.');return}const t=db.transaction('files','readwrite');for(const file of files)t.objectStore('files').put({id:uid(),file});t.oncomplete=()=>{listFiles();status('Documents sauvegardés sur cet appareil.')};t.onabort=t.onerror=()=>status('Échec de sauvegarde des documents, espace insuffisant ou stockage indisponible.')}
$('upload').onchange=e=>{addFiles(e.target.files);e.target.value=''};$('drop').ondragover=e=>e.preventDefault();$('drop').ondrop=e=>{e.preventDefault();addFiles(e.dataTransfer.files)};
render();transform();$('fit').click();
